name: delete-container-registry
description: 'Deletes the Azure Container Registry'
inputs:
  resource-group:
    description: 'Name of the Azure Resource Group'
    required: true
  registry-name:
    description: 'Name of the Azure Container Registry'
    required: true
runs:
  using: "composite"
  steps:
    - name: Mask inputs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.resource-group }}"
        echo "::add-mask::${{ inputs.registry-name }}"

    - name: Delete ACR
      shell: bash
      run: |
        az acr delete \
          --name ${{ inputs.registry-name }} \
          --resource-group ${{ inputs.resource-group }} \
          --yes
