name: Deploy on Azure Container App
description:
  'Deploy the pushed Docker image onto an Azure Container App'
inputs:
  final-image-name:
    description: 'Name of the final image'
    required: true
  final-image-tag:
    description: 'Tag of the final image'
    required: true
  container-app-name:
    description: 'Name of the Azure Container App'
    required: true
  resource-group:
    description: 'Name of the Azure Resource Group'
    required: true
  registry-url:
    description: 'URL of the Azure Container Registry'
    required: true
  registry-username:
    description: 'Username to use to login to the Azure Container Registry'
    required: true
  registry-password:
    description: 'Password to use to login to the Azure Container Registry'
    required: true
runs:
  using: "composite"
  steps:
    - name: Mask inputs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.container-app-name }}"
        echo "::add-mask::${{ inputs.resource-group }}"
        echo "::add-mask::${{ inputs.registry-name }}"
        echo "::add-mask::${{ inputs.registry-url }}"
        echo "::add-mask::${{ inputs.registry-username }}"
        echo "::add-mask::${{ inputs.registry-password }}"

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v2
      with:
        registryUrl: ${{ inputs.registry-url }}
        registryUsername: ${{ inputs.registry-username }}
        registryPassword: ${{ inputs.registry-password }}
        containerAppName: ${{ inputs.container-app-name }}
        resourceGroup: ${{ inputs.resource-group }}
        imageToDeploy: ${{ inputs.registry-url }}/${{ inputs.final-image-name }}:${{ inputs.final-image-tag }}
