// ============================================================
// Phase 2 — Container Instance only
// ============================================================

// ============================================================
// Parameters
// ============================================================

@description('Location for all resources')
param location string = resourceGroup().location

@description('Environment tag')
@allowed(['dev', 'staging', 'prod'])
param environment string

@description('Name of the Key Vault')
param keyVaultName string = ''

@description('Name of the Container Instance')
param containerInstanceName string = ''

@description('Container image to deploy (full path with tag)')
param containerImage string = ''

@description('gRPC port the container listens on')
param containerPort int = 8080

@description('Maximum number of pipeline instances')
param pipelineMaxInstances string = '1'

@description('CPU per replica')
param cpuCore string = '2'

@description('Memory per replica')
param memorySize string = '4Gi'

@description('Tags to apply to resources')
param tags object = {
    Environment: environment
    ManagedBy: 'Bicep'
    LastDeployed: utcNow('d')
  }
// ============================================================
// Resources
// ============================================================

// Reference existing Key Vault
resource keyVault 'Microsoft.KeyVault/vaults@2025-05-01' existing = {
  name: 'kv-hyb-addr-struct-grpc-${env}'
}

// Fetch secrets from Key Vault
var acrLoginServer = keyVault.getSecret('acr-login-server')
var acrUsername    = keyVault.getSecret('acr-username')
var acrPassword    = keyVault.getSecret('acr-password')

resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2025-09-01' = {
  name: containerInstanceName
  location: location
  tags: tags
  properties: {
    containers: [
      {
        name: containerInstanceName
        properties: {
          command: []
          environmentVariables: [
            {
              name: 'ds_grpc_pipeline_max_instances'
              value: pipelineMaxInstances
            }
          ]
          image: containerImage
          ports: [
            {
              port: containerPort
              protocol: 'TCP'
            }
          ]
          resources: {
            requests: {
              cpu: any(cpuCore)
              memory: memorySize
            }
          }
        }
      }
    ]
    initContainers: []
    ipAddress: {
      autoGeneratedDomainNameLabelScope: 'Noreuse'
      ports: [
        {
          port: containerPort
          protocol: 'TCP'
        }
      ]
      type: 'Public'
    }
    imageRegistryCredentials: [
      {
        server: acrLoginServer
        username: acrUsername
        password: acrPassword
      }
    ]
    osType: 'Linux'
    restartPolicy: 'Always'
    volumes: []
  }
  zones: []
}