// ============================================================
// Phase 2 — Container Instance only
// ============================================================

// ============================================================
// Parameters
// ============================================================

@description('Location for all resources')
param location string = resourceGroup().location

@description('Environment tag')
@allowed(['dev', 'staging', 'prod'])
param environment string

@description('Name of the Key Vault')
param keyVaultName string = ''

@description('Name of the Container Instance')
param containerInstanceName string = ''

@description('Container image to deploy (full path with tag)')
param containerImage string = ''

@description('gRPC port the container listens on')
param containerPort int = 8080

@description('Maximum number of pipeline instances')
param pipelineMaxInstances string = '1'

@description('CPU cores')
param cpuCore int = 2

@description('Memory in GB')
param memoryInGB int = 4

param utcShort string = utcNow('d')

// ============================================================
// Variables
// ============================================================

// Tags to apply to resources
var tags = {
  Environment: environment
  ManagedBy: 'Bicep'
  LastDeployed: utcShort
}

// ============================================================
// Resources
// ============================================================

// Reference existing Key Vault
resource keyVault 'Microsoft.KeyVault/vaults@2025-05-01' existing = {
  name: keyVaultName
}

resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2025-09-01' = {
  name: containerInstanceName
  location: location
  tags: tags
  properties: {
    containers: [
      {
        name: containerInstanceName
        properties: {
          command: []
          environmentVariables: [
            {
              name: 'ds_grpc_pipeline_max_instances'
              value: pipelineMaxInstances
            }
          ]
          image: containerImage
          ports: [
            {
              port: containerPort
              protocol: 'TCP'
            }
          ]
          resources: {
            limits: {
              cpu: any(cpuCore)
              memoryInGB: memoryInGB
            }
            requests: {
              cpu: any(cpuCore)
              memoryInGB: memoryInGB
            }
          }
        }
      }
    ]
    initContainers: []
    ipAddress: {
      autoGeneratedDomainNameLabelScope: 'Noreuse'
      ports: [
        {
          port: containerPort
          protocol: 'TCP'
        }
      ]
      type: 'Public'
    }
    imageRegistryCredentials: [
      {
        server: keyVault.getSecret('acr-login-server')
        username: keyVault.getSecret('acr-username')
        password: keyVault.getSecret('acr-password')
      }
    ]
    osType: 'Linux'
    restartPolicy: 'Always'
    volumes: []
  }
  zones: []
}