// ============================================================
// Phase 1 — Infrastructure (ACR + Key Vault)
// ============================================================

// ============================================================
// Parameters
// ============================================================

@description('Location for all resources')
param location string = resourceGroup().location

@description('Environment tag')
@allowed(['dev', 'staging', 'prod'])
param environment string

@description('Name of the Azure Container Registry')
param acrName string = ''

@allowed(['Basic', 'Classic', 'Standard', 'Premium'])
param acrSku string = 'Basic'

@description('Name of the Key Vault (3-24 chars, alphanumeric and hyphens)')
param keyVaultName string = ''

@allowed(['standard', 'premium'])
param keyVaultSku string = 'standard'

@description('Soft delete retention in days (7–90)')
@minValue(7)
@maxValue(90)
param softDeleteRetentionInDays int = 90

@description('Object ID of the Admin User')
param userId string = ''

@description('Object ID of the Service Principal')
param servicePrincipalId string = ''

param utcShort string = utcNow('d')

// ============================================================
// Variables
// ============================================================

// List of roles assignments to add to Key Vault RBAC
var roleAssignments = [
  {
    principalId:   userId
    principalType: 'User'
    role:          '00482a5a-887f-4fb3-b363-3b7fe8e74483' // Administrator
  }
  {
    principalId:   servicePrincipalId
    principalType: 'ServicePrincipal'
    role:          '4633458b-17de-408a-b874-0445c86b69e6' // SecretUser
  }
]

// Tags to apply to resources
var tags = {
  Environment: environment
  ManagedBy: 'Bicep'
  LastDeployed: utcShort
}

// ============================================================
// Resources
// ============================================================

resource acr 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: acrName
  location: location
  tags: tags
  sku: {
    name: acrSku
  }
  properties: {
    adminUserEnabled: true
    autoGeneratedDomainNameLabelScope: 'NoReuse'
  }
}

// Fetch ACR credentials using listCredentials()
var acrCredentials = acr.listCredentials()

resource keyVault 'Microsoft.KeyVault/vaults@2025-05-01' = {
  name: keyVaultName
  location: location
  tags: tags
  properties: {
    sku: {
        family: 'A'
        name: keyVaultSku
    }
    tenantId: subscription().tenantId

    enableSoftDelete: true
    enableRbacAuthorization: true
    softDeleteRetentionInDays: softDeleteRetentionInDays

    publicNetworkAccess: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
    }
  }
}

// Add all role assignments to Key Vault RBAC
resource keyVaultRoleAssignments 'Microsoft.Authorization/roleAssignments@2022-04-01' = [
  for roleAssignment in roleAssignments: {
    name: guid(keyVault.id, roleAssignment.principalId, roleAssignment.role)
    scope: keyVault
    properties: {
      roleDefinitionId: subscriptionResourceId(
        'Microsoft.Authorization/roleDefinitions',
        roleAssignment.role
      )
      principalId: roleAssignment.principalId
      principalType: roleAssignment.principalType
    }
  }
]

// Store ACR login server in Key Vault
resource acrLoginServerSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-login-server'
  properties: {
    value: acr.properties.loginServer
  }
}

// Store ACR username in Key Vault
resource acrUsernameSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-username'
  properties: {
    value: acrCredentials.username
  }
}

// Store ACR password (primary) in Key Vault
resource acrPasswordSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-password'
  properties: {
    value: acrCredentials.passwords[0].value
  }
}