// ============================================================
// Phase 1 — Infrastructure (ACR + Key Vault)
// ============================================================

// ============================================================
// Parameters
// ============================================================

@description('Location for all resources')
param location string = resourceGroup().location

@description('Environment tag')
@allowed(['dev', 'staging', 'prod'])
param environment string

@description('Name of the Azure Container Registry')
param acrName string = ''

@description('Name of the Key Vault')
param keyVaultName string = ''

@allowed(['Basic', 'Classic', 'Standard', 'Premium'])
param acrSku string = 'Basic'

@allowed(['standard', 'premium'])
param keyVaultSku string = 'standard'

// ============================================================
// Resources
// ============================================================

resource acr 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: acrName
  location: location
  sku: {
    name: acrSku
  }
  properties: {
    adminUserEnabled: true
    autoGeneratedDomainNameLabelScope: 'NoReuse'
  }
  tags: {
    environment: environment
  }
}

// Fetch ACR credentials using listCredentials()
var acrCredentials = acr.listCredentials()

resource keyVault 'Microsoft.KeyVault/vaults@2025-05-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: {
        family: 'A'
        name: keyVaultSku
    }
    tenantId: subscription().tenantId
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enableRbacAuthorization: true
  }
}

// Store ACR login server in Key Vault
resource acrLoginServerSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-login-server'
  properties: {
    value: acr.properties.loginServer
  }
}

// Store ACR username in Key Vault
resource acrUsernameSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-username'
  properties: {
    value: acrCredentials.username
  }
}

// Store ACR password (primary) in Key Vault
resource acrPasswordSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-password'
  properties: {
    value: acrCredentials.passwords[0].value
  }
}