name: test-container-deployment
description: "Tests the Container Instance by sending a ProcessAddress request"
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.13'
  resource-group:
    description: 'Name of the Azure Resource Group'
    required: true
  container-instance-name:
    description: 'Name of the Azure Container Instance'
    required: true
runs:
  using: "composite"
  steps:
    - name: Mask inputs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.container-instance-name }}"
        echo "::add-mask::${{ inputs.resource-group }}"

    - name: Fetch the Azure Container Instance's IP
      id: fetch-container-instance-ip
      shell: bash
      run: ${{ github.action_path }}/../scripts/fetch-container-instance-ip.sh
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group }}
        CONTAINER_INSTANCE_NAME: ${{ inputs.container-instance-name }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Run preprocessing scripts
      shell: bash
      run: |
        export PYTHONPATH=$(pwd)
        python ./.github/actions/scripts/test_container_deployment.py \
          --ip_address=${{ steps.fetch-container-instance-ip.outputs.container_instance_ip }}