@description('Location for the resource')
param location string

@description('Name of the Key Vault (3-24 chars, alphanumeric and hyphens)')
param keyVaultName string

@description('Name of the Managed Identity with pull assignment')
param managedIdentityName string

@description('Name of the Azure Container Registry')
param acrName string

@allowed(['Basic', 'Classic', 'Standard', 'Premium'])
param sku string

@description('Tags to apply to the Container Instance')
param tags object

// Reference existing Key Vault
resource keyVault 'Microsoft.KeyVault/vaults@2025-05-01' existing = {
  name: keyVaultName
}

// Create user-assigned Managed Identity
resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' = {
  name: managedIdentityName
  location: location
}

resource acr 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: acrName
  location: location
  tags: tags
  sku: {
    name: sku
  }
  properties: {
    adminUserEnabled: true
    autoGeneratedDomainNameLabelScope: 'NoReuse'
  }
}

// Built-in role: AcrPull
var acrPullRoleId = '7f951dda-4ed3-4680-a7ca-43fe172d538d'

// Create ACR pull role assignment
resource acrPullAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(acr.id, identity.id, acrPullRoleId)
  scope: acr
  properties: {
    roleDefinitionId: subscriptionResourceId(
        'Microsoft.Authorization/roleDefinitions',
        acrPullRoleId)
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// Fetch ACR credentials using listCredentials()
var acrCredentials = acr.listCredentials()

// Store ACR login server in Key Vault
resource acrLoginServerSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-login-server'
  properties: {
    value: acr.properties.loginServer
  }
}

// Store ACR username in Key Vault
resource acrUsernameSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-username'
  properties: {
    value: acrCredentials.username
  }
}

// Store ACR password (primary) in Key Vault
resource acrPasswordSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-password'
  properties: {
    value: acrCredentials.passwords[0].value
  }
}