@description('Location for the resource')
param location string

@description('Name of the Key Vault (3-24 chars, alphanumeric and hyphens)')
param keyVaultName string

@description('Name of the Azure Container Registry')
param acrName string

@allowed(['Basic', 'Classic', 'Standard', 'Premium'])
param sku string

@description('Tags to apply to the Container Instance')
param tags object

// Reference existing Key Vault
resource keyVault 'Microsoft.KeyVault/vaults@2025-05-01' existing = {
  name: keyVaultName
}

resource acr 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: acrName
  location: location
  tags: tags
  sku: {
    name: sku
  }
  properties: {
    adminUserEnabled: true
    autoGeneratedDomainNameLabelScope: 'NoReuse'
  }
}

// Fetch ACR credentials using listCredentials()
var acrCredentials = acr.listCredentials()

// Store ACR login server in Key Vault
resource acrLoginServerSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-login-server'
  properties: {
    value: acr.properties.loginServer
  }
}

// Store ACR username in Key Vault
resource acrUsernameSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-username'
  properties: {
    value: acrCredentials.username
  }
}

// Store ACR password (primary) in Key Vault
resource acrPasswordSecret 'Microsoft.KeyVault/vaults/secrets@2025-05-01' = {
  parent: keyVault
  name: 'acr-password'
  properties: {
    value: acrCredentials.passwords[0].value
  }
}