@description('Name of the Azure Container Registry')
param acrName string

@description('Location for the resource')
param location string

@description('Environment tag')
param environment string

@allowed(['Basic', 'Classic', 'Standard', 'Premium'])
param sku string = 'Basic'

resource acr 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: acrName
  location: location
  sku: {
    name: sku
  }
  properties: {
    adminUserEnabled: true
    autoGeneratedDomainNameLabelScope: 'NoReuse'
  }
  tags: {
    environment: environment
  }
}