@description('Location for all resources')
param location string

@description('Name of the Container Instance')
param containerInstanceName string

@description('Container image to deploy (full path with tag)')
param containerImage string

@description('gRPC port the container listens on')
param containerPort int

@description('')
@secure()
param server string

@description('Tags to apply to the Container Instance')
@secure()
param username string

@description('Tags to apply to the Container Instance')
@secure()
param password string

@description('Maximum number of pipeline instances')
param pipelineMaxInstances string

@description('CPU cores')
param cpuCore int

@description('Memory in GB')
param memoryInGB int

@description('Tags to apply to the Container Instance')
param tags object

// ============================================================
// Resources
// ============================================================

resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2025-09-01' = {
  name: containerInstanceName
  location: location
  tags: tags
  properties: {
    containers: [
      {
        name: containerInstanceName
        properties: {
          command: []
          environmentVariables: [
            {
              name: 'ds_grpc_pipeline_max_instances'
              value: pipelineMaxInstances
            }
          ]
          image: containerImage
          ports: [
            {
              port: containerPort
              protocol: 'TCP'
            }
          ]
          resources: {
            limits: {
              cpu: any(cpuCore)
              memoryInGB: memoryInGB
            }
            requests: {
              cpu: any(cpuCore)
              memoryInGB: memoryInGB
            }
          }
        }
      }
    ]
    initContainers: []
    ipAddress: {
      autoGeneratedDomainNameLabelScope: 'Noreuse'
      ports: [
        {
          port: containerPort
          protocol: 'TCP'
        }
      ]
      type: 'Public'
    }
    imageRegistryCredentials: [
      {
        server: server
        username: username
        password: password
      }
    ]
    osType: 'Linux'
    restartPolicy: 'Always'
    volumes: []
  }
  zones: []
}