name: deploy-app-infra
description: 'Deploy the Container App infrastructure using the pushed Docker image'
inputs:
  environment:
    description: 'Name of the Azure environment to deploy'
    required: true
  final-image-name:
    description: 'Name of the final image'
    required: true
  final-image-tag:
    description: 'Tag of the final image'
    required: true
  container-app-env-name:
    description: 'Name of the Azure Container App Environment'
    required: true
  container-app-name:
    description: 'Name of the Azure Container App'
    required: true
  resource-group:
    description: 'Name of the Azure Resource Group'
    required: true
  registry-name:
    description: 'Name of the Azure Container Registry'
    required: true
runs:
  using: "composite"
  steps:
    - name: Mask inputs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.container-app-env-name }}"
        echo "::add-mask::${{ inputs.container-app-name }}"
        echo "::add-mask::${{ inputs.resource-group }}"
        echo "::add-mask::${{ inputs.registry-name }}"

    - name: Fetch the Azure Container Registry's login server URL
      id: fetch-registry-url
      shell: bash
      run: ${{ github.action_path }}/../scripts/fetch-registry-url.sh
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group }}
        REGISTRY_NAME: ${{ inputs.registry-name }}

    - name: Fetch the Azure Container Registry's Admin Password
      id: fetch-registry-password
      shell: bash
      run: ${{ github.action_path }}/../scripts/fetch-registry-password.sh
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group }}
        REGISTRY_NAME: ${{ inputs.registry-name }}

    - name: Fetch the Azure Container App Environment's ID
      id: fetch-container-app-env-id
      shell: bash
      run: ${{ github.action_path }}/../scripts/fetch-container-app-env-id.sh
      env:
        CONTAINER_APP_ENV_NAME: ${{ inputs.container-app-env-name }}
        RESOURCE_GROUP: ${{ inputs.resource-group }}

    - name: Deploy Bicep (only Container App)
      id: deploy-app-infra
      uses: azure/arm-deploy@v2
      with:
        deploymentMode: 'Incremental'
        resourceGroupName: ${{ inputs.resource-group }}
        scope: 'resourcegroup'
        template: ./infra/app.bicep
        parameters: >
          ./infra/environments/${{ inputs.environment }}.app.bicepparam
          acrName=${{ inputs.registry-name }}
          acrLoginServer=${{ steps.fetch-registry-url.outputs.registry_url }}
          acrPassword=${{ steps.fetch-registry-password.outputs.registry_password }}
          containerAppEnvId=${{ steps.fetch-container-app-env-id.outputs.container_app_env_id }}
          containerAppName=${{ inputs.container-app-name }}
          containerImage=${{ steps.fetch-registry-url.outputs.registry_url }}/${{ inputs.final-image-name }}:${{ inputs.final-image-tag }}
        failOnStdErr: 'true'