# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_api.proto.address_structuring_pb2 as address__structuring__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in address_structuring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AddressStructuringStub(object):
    """Service for structuring unstructured ISO 20022 addresses into
    country and town components via a CRF + fuzzy-matching pipeline.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAddress = channel.stream_stream(
                '/address_structuring.AddressStructuring/ProcessAddress',
                request_serializer=address__structuring__pb2.AddressSample.SerializeToString,
                response_deserializer=address__structuring__pb2.ProcessAddressResult.FromString,
                _registered_method=True)


class AddressStructuringServicer(object):
    """Service for structuring unstructured ISO 20022 addresses into
    country and town components via a CRF + fuzzy-matching pipeline.
    """

    def ProcessAddress(self, request_iterator, context):
        """Bidirectional streaming: client streams address samples,
        server streams back structured results as batches complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressStructuringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAddress': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessAddress,
                    request_deserializer=address__structuring__pb2.AddressSample.FromString,
                    response_serializer=address__structuring__pb2.ProcessAddressResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'address_structuring.AddressStructuring', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('address_structuring.AddressStructuring', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AddressStructuring(object):
    """Service for structuring unstructured ISO 20022 addresses into
    country and town components via a CRF + fuzzy-matching pipeline.
    """

    @staticmethod
    def ProcessAddress(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/address_structuring.AddressStructuring/ProcessAddress',
            address__structuring__pb2.AddressSample.SerializeToString,
            address__structuring__pb2.ProcessAddressResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
