name: Build and Deploy Python to Azure Container App

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  PYTHON_VERSION: '3.13'
  APP_NAME: 'iso20022-address-structuring-grpc'
  IMAGE_NAME: 'iso20022-address-structuring-grpc'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download dependencies
        run: |
          wget -nv -P resources/raw/geonames https://download.geonames.org/export/dump/allCountries.zip
          wget -nv -P resources/raw/geonames https://download.geonames.org/export/dump/countryInfo.txt
          wget -nv -P resources/raw/geonames https://download.geonames.org/export/dump/alternateNamesV2.zip
          
          wget -nv -P resources/raw/postcodes https://download.geonames.org/export/zip/allCountries.zip
          wget -nv -P resources/raw/postcodes https://download.geonames.org/export/zip/CA_full.csv.zip
          wget -nv -P resources/raw/postcodes https://download.geonames.org/export/zip/GB_full.csv.zip
          wget -nv -P resources/raw/postcodes https://download.geonames.org/export/zip/NL_full.csv.zip
          
          wget -nv -P resources/raw/restCountries \
          https://gitlab.com/restcountries/restcountries/-/raw/master/src/main/resources/countriesV3.1.json

      - name: Explode dependencies
        run: |
          unzip resources/raw/geonames/allCountries.zip -d resources/raw/geonames
          unzip resources/raw/geonames/alternateNamesV2.zip -d resources/raw/geonames
          
          unzip resources/raw/postcodes/allCountries.zip -d resources/raw/postcodes
          unzip resources/raw/postcodes/CA_full.csv.zip -d resources/raw/postcodes
          unzip resources/raw/postcodes/GB_full.csv.zip -d resources/raw/postcodes
          unzip resources/raw/postcodes/NL_full.csv.zip -d resources/raw/postcodes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Run flake8
        run: python -m flake8 data_structuring grpc_api tests

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing scripts
        run: |
          export PYTHONPATH=$(pwd)
          python data_structuring/preprocessing/preprocess_geonames_countries.py
          python data_structuring/preprocessing/preprocess_geonames_towns.py
          python data_structuring/preprocessing/preprocess_geonames_postcodes.py
          python data_structuring/preprocessing/preprocess_rest_countries.py

      - name: Remove raw dependencies
        run: rm -rf resources/raw

      - name: Zip artifact for testing and deployment
        run: zip -r release.zip . --exclude "*.git*" --exclude "venv/*" --exclude "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install testing dependencies
        run: pip install -r requirements-test.txt

      - name: Run unit tests
        run: pytest tests/unit

      - name: Run integration tests
        run: pytest tests/integration

  push-image:
    name: Push to Azure Container Registry
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment:
      name: azure-containers

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
