name: Cleanup ACR (develop)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: develop-build-deploy
  cancel-in-progress: false

jobs:
  check-last-build:
    name: Check if enough time has passed since the last successful build
    runs-on: ubuntu-latest
    permissions:
      actions: read
    environment:
      name: azure-container-app-dev
    outputs:
      should_clean: ${{ steps.check-last-build-time.outputs.should_clean }}

    steps:
      - name: Check last build time
        id: check-last-build-time
        run: |
          GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/develop-build-deploy.yml/runs?branch=develop&per_page=1"
          
          read LAST_BUILD_TIME LAST_BUILD_STATUS < <(curl -s \
                                                          -H "Accept: application/vnd.github+json" \
                                                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                                          $GITHUB_API_URL \
                                                          | jq -r '.workflow_runs[0] | [.updated_at, .status] | @tsv')

          if [ "$LAST_BUILD_TIME" = "null" ]  || \
             [ -z "$LAST_BUILD_TIME" ]        || \
             [[ "${LAST_BUILD_STATUS}" -ne "completed" ]]
          then
            echo "No completed builds found, skipping cleanup"
            echo "should_clean=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          SECONDS_AGO=$(( $(date +%s) - $(date -d "$LAST_BUILD_TIME" +%s) ))
          echo "Last build completed $SECONDS_AGO seconds ago"

          if [ $SECONDS_AGO -ge ${{ vars.MIN_TIME_SINCE_LAST_BUILD }} ]; then
            echo "should_clean=true" >> $GITHUB_OUTPUT
          else
            echo "Last build was too recent, skipping cleanup"
            echo "should_clean=false" >> $GITHUB_OUTPUT
          fi

  cleanup:
    name: Cleanup Azure infrastructure whilst development environment is not being used
    runs-on: ubuntu-latest
    needs:
      - check-last-build
    if: needs.check-last-build.outputs.should_clean == 'true'
    permissions:
      actions: read
    environment:
      name: azure-container-app-dev

    steps:
      - uses: actions/checkout@v6

      - name: Log in to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/delete-container-app
        with:
          container-app-name: ${{ secrets.CONTAINER_APP_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}

      - uses: ./.github/actions/delete-container-registry
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          registry-name: ${{ secrets.REGISTRY_NAME }}

      - name: Logout of Azure
        shell: bash
        run: az logout
