name: CI/CD to ACR/ACA (develop)

on:
  push:
    branches: [ develop ]
  # Run nightly build at 2:00 AM UTC every night
  # schedule:
  #   - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: develop-build-deploy
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.13'
  ARTIFACT_NAME: 'iso-address-structuring-grpc-${{ github.run_id }}'
  BASE_IMAGE_NAME: 'base-image-${{ github.run_id }}'
  BASE_IMAGE_TAG: ${{ github.sha }}
  FINAL_IMAGE_NAME: 'iso20022-address-structuring-grpc'
  FINAL_IMAGE_TAG: ${{ github.sha }}

jobs:
  main-infra:
    name: Deploy main infrastructure via ARM
    runs-on: ubuntu-latest
    environment:
      name: azure-container-app-dev

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/deploy-main-infra
        id: deploy-main-infra
        with:
          environment: ${{ vars.ENVIRONMENT }}
          container-app-env-name: ${{ secrets.CONTAINER_APP_ENV_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          registry-name: ${{ secrets.REGISTRY_NAME }}

      - name: Logout of Azure
        shell: bash
        run: az logout

  build-base-image:
    name: Build base Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build-base-image
        with:
          base-image-name: ${{ env.BASE_IMAGE_NAME }}
          base-image-tag: ${{ env.BASE_IMAGE_TAG }}

  build-python:
    name: Build Python Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: ./.github/actions/build-app
        with:
          artifact-name: ${{ env.ARTIFACT_NAME }}

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs:
      - build-python

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/run-unit-tests
        with:
          artifact-name: ${{ env.ARTIFACT_NAME }}

  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs:
      - unit-test

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/run-integration-tests
        with:
          artifact-name: ${{ env.ARTIFACT_NAME }}

  push-image:
    name: Push to Azure Container Registry
    runs-on: ubuntu-latest
    needs:
      - main-infra
      - build-base-image
      - integration-test
    environment:
      name: azure-container-app-dev

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/push-docker-image
        with:
          artifact-name: ${{ env.ARTIFACT_NAME }}
          base-image-name: ${{ env.BASE_IMAGE_NAME }}
          base-image-tag: ${{ env.BASE_IMAGE_TAG }}
          final-image-name: ${{ env.FINAL_IMAGE_NAME }}
          final-image-tag: ${{ env.FINAL_IMAGE_TAG }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          registry-name: ${{ secrets.REGISTRY_NAME }}

      - name: Logout of Azure
        shell: bash
        run: az logout

  app-infra:
    name: Deploy app infrastructure via ARM
    runs-on: ubuntu-latest
    needs:
      - main-infra
      - push-image
    environment:
      name: azure-container-app-dev

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/deploy-app-infra
        with:
          environment: ${{ vars.ENVIRONMENT }}
          final-image-name: ${{ env.FINAL_IMAGE_NAME }}
          final-image-tag: ${{ env.FINAL_IMAGE_TAG }}
          container-app-env-name: ${{ secrets.CONTAINER_APP_ENV_NAME }}
          container-app-name: ${{ secrets.CONTAINER_APP_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          registry-name: ${{ secrets.REGISTRY_NAME }}

      - name: Logout of Azure
        shell: bash
        run: az logout

  remove-prev-images:
    name: Remove previous Docker images
    runs-on: ubuntu-latest
    needs:
      - app-infra
    environment:
      name: azure-container-app-dev

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/delete-prev-images
        with:
          final-image-name: ${{ env.FINAL_IMAGE_NAME }}
          registry-name: ${{ secrets.REGISTRY_NAME }}

      - name: Logout of Azure
        shell: bash
        run: az logout

  test-container-app:
    name: Test the deployed Container App
    runs-on: ubuntu-latest
    needs:
      - app-infra
    environment:
      name: azure-container-app-dev

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/test-container-app
        with:
          container-app-name: ${{ secrets.CONTAINER_APP_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}

      - name: Logout of Azure
        shell: bash
        run: az logout
